USE master
GO
if exists (select * from sysdatabases where name='FORUM')
	DROP DATABASE FORUM
GO

CREATE DATABASE FORUM
GO
USE FORUM
GO

CREATE TABLE COMMENT(
id int IDENTITY(1, 1) NOT NULL PRIMARY KEY,
content TEXT NOT NULL);

CREATE TABLE POST(
id int IDENTITY(1, 1) NOT NULL PRIMARY KEY,
title VARCHAR(255) NOT NULL, 
post_description VARCHAR(255) NOT NULL,
likes int NOT NULL, 
dislikes int NOT NULL,
fk_comment_id int FOREIGN KEY REFERENCES COMMENT(id) ON DELETE CASCADE);

CREATE TABLE ACCOUNT(
id int IDENTITY(1, 1) NOT NULL PRIMARY KEY,
username VARCHAR(255) UNIQUE NOT NULL,
account_password VARCHAR(255) NOT NULL, 
email VARCHAR(255) NOT NULL,
profile_pic_path TEXT NOT NULL, 
fk_post_id int FOREIGN KEY REFERENCES POST(id) ON DELETE CASCADE);

CREATE TABLE ACCOUNT_ROLE(
account_id int, 
role_id int, 
CONSTRAINT ROLE_OF_ACCOUNT PRIMARY KEY(account_id, role_id),
CONSTRAINT FK_ROLE_OF_ACCOUNT_ACCOUNT_ID FOREIGN KEY(account_id) REFERENCES ACCOUNT(id) ON DELETE CASCADE,
CONSTRAINT FK_ROLE_OF_ACCOUNT_ROLE_ID FOREIGN KEY(role_id) REFERENCES ROLES(id) ON DELETE CASCADE);

CREATE TABLE TOPIC(
id int IDENTITY(1, 1) NOT NULL PRIMARY KEY,
topic_name VARCHAR(255) NOT NULL);

CREATE TABLE TOPIC_POST(
topic_id int, 
post_id int, 
CONSTRAINT POST_OF_TOPIC PRIMARY KEY(topic_id, post_id),
CONSTRAINT FK_POST_OF_TOPIC_TOPIC_ID FOREIGN KEY(topic_id) REFERENCES TOPIC(id) ON DELETE CASCADE,
CONSTRAINT FK_POST_OF_TOPIC_POST_ID FOREIGN KEY(post_id) REFERENCES POST(id) ON DELETE CASCADE);

INSERT INTO POST (title, post_description, likes, dislikes)
VALUES ('Weather', 'QWEQWE', 123, 12);

INSERT INTO ACCOUNT (username, account_password, email, profile_pic_path, fk_post_id)
VALUES ('Staskata', '123123', 'stat@gmail.com', '1123123123', '1');

INSERT INTO ROLES(rolename)
VALUES ('ADMIN');

INSERT INTO ACCOUNT_ROLE(account_id, role_id)
VALUES (1, 1);

CREATE TABLE ROLES(
id int IDENTITY(1, 1) NOT NULL PRIMARY KEY,
rolename VARCHAR(255) NOT NULL);

DELETE FROM ACCOUNT WHERE ( ACCOUNT.id = '1');