GO
if exists (select * from sysdatabases where name='Musical Collection DB')
	DROP DATABASE [Musical Collection DB]
GO
USE master

CREATE DATABASE [Musical Collection DB]
GO
USE [Musical Collection DB]
GO

CREATE TABLE ALBUM(
ID int IDENTITY(1, 1) NOT NULL PRIMARY KEY, 
NAME VARCHAR(255) NOT NULL);

CREATE TABLE SONG_GENRES(
ID int IDENTITY(1, 1) NOT NULL PRIMARY KEY,
GENRE VARCHAR(255) NOT NULL); 

CREATE TABLE SONGS(
ID int IDENTITY(1, 1) NOT NULL PRIMARY KEY,
NAME VARCHAR(255) NOT NULL UNIQUE,
GENRE_ID int FOREIGN KEY(GENRE_ID) REFERENCES SONG_GENRES(ID) NOT NULL,
DURATION TIME(0) NOT NULL, 
RELEASE_DATE DATE NOT NULL,
ALBUM_ID int FOREIGN KEY(ALBUM_ID) REFERENCES ALBUM(ID) NULL);

CREATE TABLE PLAYLIST(
ID int IDENTITY(1, 1) NOT NULL PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
CREATOR VARCHAR(255) NOT NULL);

CREATE TABLE LISTENER(
ID int IDENTITY(1, 1) NOT NULL PRIMARY KEY, 
USERNAME VARCHAR(255) NOT NULL UNIQUE, 
PASSWORD VARCHAR(255) NOT NULL,
FULLNAME VARCHAR(255) NOT NULL,
BIRTHDATE DATE NOT NULL,
ACTIVE BIT NOT NULL);

CREATE TABLE AUTHOR(
ID int IDENTITY(1, 1) NOT NULL PRIMARY KEY,
USERNAME VARCHAR(255) NOT NULL UNIQUE, 
PASSWORD VARCHAR(255) NOT NULL,
FULLNAME VARCHAR(255) NOT NULL,
BIRTHDATE DATE NOT NULL,
ACTIVE BIT NOT NULL)


CREATE TABLE SONGS_IN_PLAYLIST(
PLAYLIST_ID int,
SONG_ID int,
CONSTRAINT SONG_IN_PLAYLIST_PK PRIMARY KEY(PLAYLIST_ID, SONG_ID),
CONSTRAINT FK_PLAYLIST_ID FOREIGN KEY(PLAYLIST_ID) REFERENCES PLAYLIST(ID),
CONSTRAINT FK_SONG_ID FOREIGN KEY(SONG_ID) REFERENCES SONGS(ID));

CREATE TABLE PLAYLIST_OF_LISTENER(
PLAYLIST_ID int,
LISTENER_ID int,
CONSTRAINT LISTENER_PLAYLISTS_PK PRIMARY KEY(PLAYLIST_ID, LISTENER_ID),
CONSTRAINT FK_PLAYLIST_LISTENER_ID FOREIGN KEY(PLAYLIST_ID) REFERENCES PLAYLIST(ID),
CONSTRAINT FK_LISNERER_PLAYLYST_ID FOREIGN KEY(LISTENER_ID) REFERENCES LISTENER(ID));

CREATE TABLE ALBUMS_OF_AUTHORS(
AUTHOR_ID int,
ALBUM_ID int,
CONSTRAINT ARTIST_ALBUMS_PK PRIMARY KEY(ALBUM_ID, AUTHOR_ID),
CONSTRAINT FK_ALBUM_ID FOREIGN KEY(ALBUM_ID) REFERENCES ALBUM(ID),
CONSTRAINT FK_AUTHOR_ID FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHOR(ID));

CREATE TABLE SONGS_OF_ARTISTS(
AUTHOR_ID int,
SONG_ID int,
CONSTRAINT SONGS_OF_ARTIST_PK PRIMARY KEY(SONG_ID, AUTHOR_ID),
CONSTRAINT FK_SONG_OF_ARTIST_ID FOREIGN KEY(SONG_ID) REFERENCES SONGS(ID),
CONSTRAINT FK_AUTHOR_OF_SONG_ID FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHOR(ID));

CREATE TABLE LISTENER_FAVOURITE_GENRES(
LISTENER_ID int,
SONG_GENRE int,
CONSTRAINT LISTENER_FAVOURITE_GENRES_PK PRIMARY KEY(LISTENER_ID, SONG_GENRE),
CONSTRAINT FK_LISTENER_ID FOREIGN KEY(LISTENER_ID) REFERENCES LISTENER(ID),
CONSTRAINT FK_FAVOURITE_GENRES_ID FOREIGN KEY(SONG_GENRE) REFERENCES SONG_GENRES(ID));

CREATE TABLE LISTENER_FAVOURITE_SONGS(
LISTENER_ID int,
SONG_ID int,
CONSTRAINT LISTENER_FAVOURITE_SONGS_PK PRIMARY KEY(LISTENER_ID, SONG_ID),
CONSTRAINT FK_LISTENER_FAVOURITE_SONGS_ID FOREIGN KEY(LISTENER_ID) REFERENCES LISTENER(ID),
CONSTRAINT FK_FAVOURITE_SONGS_ID FOREIGN KEY(SONG_ID) REFERENCES SONG_GENRES(ID));

