USE master
GO
if exists (select * from sysdatabases where name='Musical Collection DB')
	DROP DATABASE [Musical Collection DB]
GO

CREATE DATABASE [Musical Collection DB]
GO
USE [Musical Collection DB]
GO

CREATE TABLE SONGS(
ID int IDENTITY(1, 1) NOT NULL PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
GENRE VARCHAR(255) NOT NULL,
DURATION TIME(0) NOT NULL, 
RELEASE_DATE DATE NOT NULL);

CREATE TABLE PLAYLIST(
ID int IDENTITY(1, 1) NOT NULL PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
CREATOR VARCHAR(255) NOT NULL);

CREATE TABLE ALBUM(
ID int IDENTITY(1, 1) NOT NULL PRIMARY KEY, 
NAME VARCHAR(255) NOT NULL);

CREATE TABLE LISTENER(
ID int IDENTITY(1, 1) NOT NULL PRIMARY KEY, 
USERNAME VARCHAR(255) NOT NULL, 
PASSWORD VARCHAR(255) NOT NULL,
FULLNAME VARCHAR(255) NOT NULL,
BIRTHDATE DATE NOT NULL,
ACTIVE BIT NOT NULL);

CREATE TABLE AUTHOR(
ID int IDENTITY(1, 1) NOT NULL PRIMARY KEY,
USERNAME VARCHAR(255) NOT NULL, 
PASSWORD VARCHAR(255) NOT NULL,
FULLNAME VARCHAR(255) NOT NULL,
BIRTHDATE DATE NOT NULL,
ACTIVE BIT NOT NULL)

CREATE TABLE SONGS_IN_PLAYLIST(
PLAYLIST_ID int,
SONG_ID int,
CONSTRAINT SONG_IN_PLAYLIST_PK PRIMARY KEY(PLAYLIST_ID, SONG_ID),
CONSTRAINT FK_PLAYLIST_ID FOREIGN KEY(PLAYLIST_ID) REFERENCES PLAYLIST(ID),
CONSTRAINT FK_SONG_ID FOREIGN KEY(SONG_ID) REFERENCES SONGS(ID));

ALTER TABLE SONGS WITH NOCHECK
ADD ALBUM_ID VARCHAR(255) FOREIGN KEY(ID) REFERENCES ALBUM(ID)

CREATE TABLE PLAYLIST_OF_LISTENER(
PLAYLIST_ID int,
LISTENER_ID int,
CONSTRAINT LISTENER_PLAYLISTS_PK PRIMARY KEY(PLAYLIST_ID, LISTENER_ID),
CONSTRAINT FK_PLAYLIST_LISTENER_ID FOREIGN KEY(PLAYLIST_ID) REFERENCES PLAYLIST(ID),
CONSTRAINT FK_LISNERER_PLAYLYST_ID FOREIGN KEY(LISTENER_ID) REFERENCES LISTENER(ID));

CREATE TABLE ALBUMS_OF_AUTHORS(
AUTHOR_ID int,
ALBUM_ID int,
CONSTRAINT ARTIST_ALBUMS_PK PRIMARY KEY(ALBUM_ID, AUTHOR_ID),
CONSTRAINT FK_ALBUM_ID FOREIGN KEY(ALBUM_ID) REFERENCES ALBUM(ID),
CONSTRAINT FK_AUTHOR_ID FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHOR(ID));

CREATE TABLE SONGS_OF_ARTISTS(
AUTHOR_ID int,
SONG_ID int,
CONSTRAINT SONGS_OF_ARTIST_PK PRIMARY KEY(SONG_ID, AUTHOR_ID),
CONSTRAINT FK_SONG_OF_ARTIST_ID FOREIGN KEY(SONG_ID) REFERENCES SONGS(ID),
CONSTRAINT FK_AUTHOR_OF_SONG_ID FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHOR(ID));

--ALTER TABLE LISTENER
--ADD FAVOURITE_GENRES VARCHAR(255) FOREIGN KEY(FAVOURITE_GENRES) REFERENCES SONGS(GENRES), 
--ADD FAVOURITE_SONGS VARCHAR(255) FOREIGN KEY(FAVOURITE_SONGS) REFERENCES SONGS(NAME),
--ADD FAVOURITE_GENRES VARCHAR(255) FOREIGN KEY(FAVOURITE_GENRES) REFERENCES SONGS(GENRES)

INSERT INTO SONGS VALUES
('NA TEBE NE OTKAZVAM', 'CHALGA', 03:57, '2015-08-23')
ON DUPLICATE KEY UPDATE SONGS.NAME;
