USE FORUM 

-- requires post table to execute first--
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_NAME = 'ACCOUNT')
BEGIN
CREATE TABLE ACCOUNT(
id int IDENTITY(1, 1) NOT NULL PRIMARY KEY,
username NVARCHAR(255) UNIQUE NOT NULL,
account_password NVARCHAR(255) NOT NULL, 
email NVARCHAR(255) UNIQUE NOT NULL,
profile_pic_path TEXT NOT NULL, 
points int NOT NULL,  
fk_post_id int FOREIGN KEY REFERENCES POST(id) ON DELETE CASCADE)
END