USE FORUM

--requires role and account table to be created first--
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_NAME = 'ACCOUNT_ROLE')
BEGIN
CREATE TABLE ACCOUNT_ROLE(
account_id int, 
role_id int, 
CONSTRAINT ROLE_OF_ACCOUNT PRIMARY KEY(account_id, role_id),
CONSTRAINT FK_ROLE_OF_ACCOUNT_ACCOUNT_ID FOREIGN KEY(account_id) REFERENCES ACCOUNT(id) ON DELETE CASCADE,
CONSTRAINT FK_ROLE_OF_ACCOUNT_ROLE_ID FOREIGN KEY(role_id) REFERENCES ROLES(id) ON DELETE CASCADE)
END
