USE FORUM 

-- requires post table to execute first--
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_NAME = 'ACCOUNT')
BEGIN
CREATE TABLE ACCOUNT(
id uniqueIdentifier DEFAULT (NEWID()) PRIMARY KEY,
username NVARCHAR(255) UNIQUE NOT NULL,
account_password NVARCHAR(255) NOT NULL, 
email NVARCHAR(255) UNIQUE NOT NULL,
profile_pic_path TEXT NOT NULL, 
points int DEFAULT 0)
END