USE FORUM

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_NAME = 'COMMENT')
BEGIN
CREATE TABLE COMMENT(
id uniqueIdentifier DEFAULT (NEWID()) PRIMARY KEY,
content TEXT NOT NULL,
fk_post_id uniqueIdentifier FOREIGN KEY REFERENCES POST(id)
ON DELETE CASCADE)
END