USE FORUM

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_NAME = 'COMMENT')
BEGIN
CREATE TABLE COMMENT(
id uniqueIdentifier DEFAULT (NEWID()) PRIMARY KEY,
content TEXT NOT NULL,
post_id uniqueIdentifier 
CONSTRAINT fk_comment_post_id FOREIGN KEY REFERENCES POST(id) ON DELETE CASCADE,
react_id uniqueIdentifier UNIQUE
CONSTRAINT fk_comment_react_id FOREIGN KEY REFERENCES REACT(id) ON UPDATE CASCADE)
END