USE FORUM 

--Requires comment table to be created first--
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_NAME = 'POST')
BEGIN
CREATE TABLE POST(
id uniqueIdentifier DEFAULT (NEWID()) PRIMARY KEY,
title NVARCHAR(255) NOT NULL, 
account_id uniqueIdentifier,
CONSTRAINT fk_account_id FOREIGN KEY(account_id) REFERENCES ACCOUNT(id) ON DELETE CASCADE);
END

