USE FORUM 

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_NAME = 'POST_REACT')
BEGIN
CREATE TABLE POST_REACT(
post_id uniqueIdentifier UNIQUE,
react_id uniqueIdentifier UNIQUE, 
PRIMARY KEY(post_id, react_id),
CONSTRAINT FK_POST_REACT_POST_ID FOREIGN KEY(post_id)
REFERENCES POST(id) ON DELETE CASCADE,
CONSTRAINT FK_POST_REACT_REACT_ID FOREIGN KEY(react_id)
REFERENCES REACT(id) ON DELETE CASCADE);
END