USE FORUM 

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_NAME = 'POSTS')
BEGIN
	CREATE TABLE POSTS(
	post_id uniqueIdentifier DEFAULT (NEWID()) PRIMARY KEY,
	post_title NVARCHAR(255) NOT NULL UNIQUE, 
	post_description TEXT NOT NULL,
	post_account_id uniqueIdentifier NOT NULL,
	post_topic_id uniqueIdentifier DEFAULT NULL);

	ALTER TABLE POSTS ADD CONSTRAINT FK_POSTS_ACCOUNT_ID 
	FOREIGN KEY(post_account_id) REFERENCES ACCOUNTS(account_id) ON DELETE CASCADE;

	ALTER TABLE POSTS ADD CONSTRAINT FK_POSTS_TOPIC_ID 
	FOREIGN KEY(post_topic_id) REFERENCES TOPICS(topic_id) ON UPDATE CASCADE;
END

