USE FORUM 

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_NAME = 'COMMENT_REACT')
BEGIN
CREATE TABLE COMMENT_REACT(
comment_id uniqueIdentifier UNIQUE,
react_id uniqueIdentifier UNIQUE, 
PRIMARY KEY(comment_id, react_id),
CONSTRAINT FK_COMMENT_REACT_COMMENT_ID FOREIGN KEY(comment_id)
REFERENCES COMMENT(id) ON DELETE CASCADE,
CONSTRAINT FK_COMMENT_REACT_REACT_ID FOREIGN KEY(react_id)
REFERENCES REACT(id) ON DELETE CASCADE);
END