USE FORUM

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_NAME = 'ROLES')
BEGIN
CREATE TABLE ROLES(
id int IDENTITY(1, 1) NOT NULL PRIMARY KEY,
rolename VARCHAR(255) NOT NULL)
END
