USE FORUM 

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_NAME = 'TOPIC')
BEGIN
CREATE TABLE TOPIC(
id int IDENTITY(1, 1) NOT NULL PRIMARY KEY,
topic_name VARCHAR(255) NOT NULL)
END