USE FORUM 

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_NAME = 'TOPIC')
BEGIN
CREATE TABLE TOPIC(
id uniqueIdentifier DEFAULT (NEWID()) PRIMARY KEY,
topic_name NVARCHAR(255) UNIQUE NOT NULL,
topic_description text NOT NULL,
topic_owner uniqueIdentifier FOREIGN KEY REFERENCES ACCOUNT(id) ON DELETE CASCADE)
END